openapi: 3.0.0
info:
  title: react, sequalize and express 
  description: an explorer for our project 
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Optional server description, e.g. Main (production) server
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

    post:
      summary: create new user.
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
      responses:
        '200':    # status code
          description: A JSON array of user names
      

    # post:
    #   description: Optional extended description in CommonMark or HTML.
    #   # requestBody:
    #   #   content:
    #   #     application/json:
    #   #       schema:
    #   #         type: string
    #           # type: object
    #           # properties:
    #           #   id:
    #           #     type: integer
    #           #   name:
    #           #     type: string
    #   responses:
    #     '201':
    #       description: Created

    # post:
    # summary: Add a new user
    # parameters:
    # - name: userObj
    #   required: true
    #   in: body
    #   type: object
    #   schema:
    #     UserInfo:
    #       properties:
    #           name:
    #             type: string
    # responses:
    #   '201':
    #     description: Created



    # post:
    # consumes:
    #   - application/json
    # produces:
    #   - application/json
    #   - text/xml
    #   - text/html
    # parameters:
    #   - name: body
    #     in: body
    #     required: true
    #     schema:
    #       # Body schema with atomic property examples
    #       type: object
    #       properties:
    #         testapi:
    #           type: object
    #           properties:
    #             messageId:
    #               type: string
    #               example: kkkk8
    #             messageDateTime:
    #               type: string
    #               example: '2014-08-17T14:07:30+0530'
    #         testapiBody:
    #           type: object
    #           properties:
    #             cameraServiceRq:
    #               type: object
    #               properties:
    #                 osType:
    #                   type: string
    #                   example: android
    #                 deviceType:
    #                   type: string
    #                   example: samsung555

